import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import type { Metadata } from "next";
import { Suspense } from "react";
import { Providers } from "./providers";
import AppFooter from "@/components/common/AppFooter";
import AppHeader from "@/components/common/AppHeader/AppHeader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Markus Löffler", url: "https://github.com/MarkusLoeffler01/Ventry"}]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased"
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider>
          <Suspense fallback={null}>
            <Providers>
              <AppHeader />
              <main style={{ display: "flex", flex: "1 0 auto", flexDirection: "column" }}>
                {/* Spacer so page content is never hidden under the fixed AppBar */}
                <div style={{ height: 64 }} />
                {children}
              </main>
              <AppFooter />
            </Providers>
          </Suspense>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
